package com.asv.enums;

/**
 * Состояния (шаги) внутри активного процесса.
 * Каждое состояние соответствует конкретному ожидаемому вводу от пользователя.
 * Сохранён в точности как в твоём коде.
 */
public enum ProcessState {
    NONE

    ,BOOKING_ENTERING_CHECK_IN_DATE
    ,BOOKING_ENTERING_CHECK_OUT_DATE
    ,BOOKING_ENTERING_QUANTITY_PERSONS
    ,BOOKING_ENTERING_ROOM_NUMBER
    ,BOOKING_ENTERING_PROMO_CODE
    ,BOOKING_ENTERING_SERVICES
    ,BOOKING_ENTERING_GUEST_NAME
    ,BOOKING_ENTERING_GUEST_SURNAME
    ,BOOKING_ENTERING_GUEST_AGE
    ,BOOKING_ENTERING_GUEST_DOCUMENT


    ,REGISTRATION_ENTERING_NICK_NAME
    ,REGISTRATION_ENTERING_NAME
    ,REGISTRATION_ENTERING_FATHERS_NAME
    ,REGISTRATION_ENTERING_FAMILY_NAME
    ,REGISTRATION_ENTERING_EMAIL
    ,REGISTRATION_ENTERING_PHONE_NUMBER
    ,REGISTRATION_ENTERING_PASSWORD

    ,SIGN_IN_ENTERING_LOGIN
    ,SIGN_IN_ENTERING_PASSWORD

    ,REQUEST_ROOM_NUMBER
    ,REQUEST_SERVICE_DESCR

    ,GET_ROOM_INFO_ENTERING_NUMBER

    ,GET_SERVICE_INFO_ENTERING_NAME

    ,GET_FREE_ROOMS_ENTERING_CHECK_IN_DATE
    ,GET_FREE_ROOMS_ENTERING_CHECK_OUT_DATE

    ,VIEW_BOOKING_ENTERING_ID
    ,DELETE_BOOKING_ENTERING_ID


}
