version: '3.8'

services:
  # PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: hotel-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-hotel_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_:/var/lib/postgresql/data
#      - убрано ,так как при запуске первым запускается развертывание бд, а потом создание таблиц,таблицы создаются
#        через Hibernate , каждого приложения, и загружаются оттуда
#      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Discovery Server
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8081:8081"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 3

  # Config Server
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8082:8082"
    volumes:
      - ./config-service/src/main/resources/services:/config/services:ro
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 3

  # Hotel Service
  hotel:
    build:
      context: ./hotel
      dockerfile: Dockerfile
    container_name: hotel-service
    ports:
      - "8080:8083"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8081/eureka/
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      ACCEESS_SECRET: ${ACCEESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP: ${MAIL_SMTP}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
    depends_on:
      config-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 3

  # Telegram Service
  tg-service:
    build:
      context: ./tg-service
      dockerfile: Dockerfile
    container_name: tg-service
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8081/eureka/
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TG_TOKEN: ${TG_TOKEN}
      TG_BOT_NAME: ${TG_BOT_NAME}
    depends_on:
      config-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 3

networks:
  hotel-network:
    driver: bridge

volumes:
  postgres_: