server.port=8081

# Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Global CORS configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*

# Routes configuration
spring.cloud.gateway.routes[0].id=discovery-service-route
spring.cloud.gateway.routes[0].uri=lb://discovery-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka/**

spring.cloud.gateway.routes[1].id=config-service-route
spring.cloud.gateway.routes[1].uri=lb://config-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/config/**

spring.cloud.gateway.routes[2].id=hotel-service
spring.cloud.gateway.routes[2].uri=lb://hotel
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/hotel/**

# Timeout
spring.cloud.gateway.httpclient.connect-timeout=1000
spring.cloud.gateway.httpclient.response-timeout=5000