server.port=8083
spring.application.name=hotel
#spring.profiles.active=prod

#  Config Server
spring.config.import=configserver:http://localhost:8082

# SPRING DATASOURCE CONFIGURATION

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.eureka-server-connect-timeout-seconds=10
eureka.client.eureka-server-read-timeout-seconds=15
eureka.instance.prefer-ip-address=true