server.port=8082

spring.application.name=config-service
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=classpath:/services
spring.cloud.config.enabled=true

## Eureka
#eureka.client.service-url.defaultZone=http://discovery-service:8081/eureka/
#eureka.client.eureka-server-connect-timeout-seconds=10
#eureka.client.eureka-server-read-timeout-seconds=15
#eureka.instance.prefer-ip-address=true

# Actuator settings  http://localhost:8082/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

#Logging
logging.level.org.springframework.cloud.config=ERROR
